# Generated by Django 3.1.2 on 2020-10-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_like',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
