# Generated by Django 3.1.2 on 2020-10-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_total_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='total_like',
            new_name='total_likes',
        ),
    ]
